# Site
title:              IEMS 97 cohort
bio:                'Play the Game'
description:        "We describe ourselves"


theme: jekyll-theme-merlot

# Google Analytics
google_analytics: UA—173255588-1

# Social
analytics-id:       "default"
twitter:            default
facebook:           default
instagram:          default
github:             default

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  
 
 
jekyll-mentions:
    base_url: https://github.com
